# Generated by Django 3.2.13 on 2023-05-25 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230522_0926'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
