# Generated by Django 3.2.13 on 2023-06-15 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_movie_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='created_by',
        ),
    ]
